# 1. Introduction to Python Types and Operations

## Learning Objectives

This week, we're stepping into exciting landscape of Python coding! Our journey will spotlight the unique features of Python and how it differs from our old friend, Matlab.

By the end of this week we expect you to understand how to:

- Manipulate simple variable types, operators and conditions
- Use Python lists and Dictionaries
- Write loops and functions
- Understand modules, packages and classes
- Be familiar with the NumPy, Matplotlib and Pandas modules
- Read and write to and from files

## Basics

### Switching from Matlab to Python

Switching languages might sound intimidating, but let's put your mind at ease - Matlab and Python have quite a bit in common. To illustrate this, here's a handy cheat sheet that draws parallels between the two. Trust me, you'll find the transition smoother than you think! [cheat sheet](https://mas-dse.github.io/DSE200/cheat_sheets/1_python/6_2_NumPy_for_MATLAB_users.pdf)

![title](https://raw.githubusercontent.com/SirTurtle/ML-BME-UofA-imgs/main/Week-1-Python-programming/imgs/matlabtopython.png)

Here the key differences I seek to emphasize are that:

1. Python isn't fond of semicolons at the end of each line. Python does not require semicolons at the end of each line to prevent the interpreter from printing out the values of each variable

2. Python is all about clean, simple structure, so it uses only indentation to control the flow of the code. You won't find any end statements closing off if/for/while instructions here (no ```end``` statements at the end of ```if/for/while``` statements), unlike in Matlab.

3. In Python land, array indexing starts from 0, not 1.

All of these points will be covered in more detail later as we progress through the notebooks.

### Python: A User-Friendly Language

One of Python's main goals is to be reader-friendly (easy to read and use) and intuitive. It takes pride in its simplicity.

There's no better way to showcase this than with the classic 'Hello World' example. If you want to print 'Hello world' in Python, all you need is the print function:

In [1]:
print("Hello World")

Hello World


In contrast if we look at C++, things get a bit more complicated. The iconic 'Hello World' program in C++ involves multiple lines of code, the need to import standard libraries, and here's the kicker - you can't run it until you've compiled it:

```c++
#include <iostream>
using namespace std;

int main()
{
    cout << "Hello, World!";
    return 0;
}
```

 ###  Commenting

Finally, before we learn any syntax! Remember, no matter what language you're coding in, comments are crucial. They make your code readable and user-friendly to others. In Python, we use ```#``` to indicate a comment. Let's keep our code tidy and understandable, shall we?

In [2]:
# this is a code comment

Besides explaining what lines of code do, we also use comments throughout all the Exercise sections. They're your helpful guide, indicating where you need to add code and providing clear instructions on what needs to be accomplished. Let's think of them as your friendly road signs on this coding journey!


As we move forward in this notebook, we'll be uncovering the secrets of simple variables, lists, strings, and dictionary types. And that's not all! By the end, we'll have explored math operators, conditions, functions, and the basics of input/output statements. This is going to be a fun ride, so let's get started!

## 1.1. Variables and Types

In Python, we have three kinds of numbers we can work with:
- Integers
- Floats
- Complex numbers (though we won't be using these in this course)

Here's how you can assign an integer value to a variable:

In [3]:
myint = 5

Here's how you can declare float variables:

In [4]:
myfloat1 = 12.1
myfloat2 = float(myint) # casting an integer type as float

Let's print the variable types and values.

In [5]:
# see the difference between float and int variables
print('myint has type {} and value {}'.format(type(myint), myint))
print('myfloat1 has type {} and value {}'.format(type(myfloat1), myfloat1))
print('myfloat2 has type {} and value {}'.format(type(myfloat2), myfloat2))

myint has type <class 'int'> and value 5
myfloat1 has type <class 'float'> and value 12.1
myfloat2 has type <class 'float'> and value 5.0


In the examples we've seen, `myint` and `myfloat` are what we call variables. They're like placeholders for the values we assign to them.

### Strings

Strings (of characters) are defined either with a single quote or a double quotes e.g.

In [6]:
string1 = "Hello, World!"
string2 = 'Hello, World!'
print(string1)
print(string2)
print('Testing if string1 and string2 are equal:', string1 == string2)

Hello, World!
Hello, World!
Testing if string1 and string2 are equal: True


If you need an apostrophe (single quote) inside a string, the easiest way is to enclose the string in double quotes (and vice versa):

In [7]:
string1 = "Steve's dog"
print(string1)

Steve's dog


You can also use \ to enter an escape sequence to include a special characters:

In [8]:
string1 = "This string includes a double-quote \" and a backslash \\"
print(string1)

This string includes a double-quote " and a backslash \


We can also define multi-line strings, using triple quotes (''' or """).

In [9]:
multiline_string = '''This is a string
that extends across
multiple lines'''
print(multiline_string)

This is a string
that extends across
multiple lines


### Format Strings

Sometimes, we'll need to format our output with printed statements. That's when the ```format``` (or ``` str.format ```) method for strings comes in handy. This neat trick allows us to incorporate different data types within the string, and even control the precision of floats (truncating the precision of floats). Here's an example:

In [10]:
print('The second argument is {1}, the first argument is {0}'.format(1, 2))
print('Two is {two}, one is {one}'.format(one=1, two=2))
print('Pi is about {}'.format(3.14159)) # argument positions and types don't need to specified
print('Pi is about {0:7.2f}'.format(3.14159))

The second argument is 2, the first argument is 1
Two is 2, one is 1
Pi is about 3.14159
Pi is about    3.14


The general syntax for a format placeholder is:

```[argument]:[width][.precision]type```

In the example ```print('Pi is about {0:7.2f}'.format(3.14159))```: 0 is the position of the argument, 7 is the width (if the width is longer than the number padding, in the form of spaces are added in front of the number), 2 is the number of decimal places and ```f``` is the type. Examples of common types include

- ```d``` signed integer decimal e.g. an integer would be formatted as ```{d} ```
- ```s``` string
- ```f``` floating point decimal

For more examples see https://www.python-course.eu/python3_formatted_output.php

**To do**

- Try changing the width and decimal place parameters above to observe their effect. Why not try writing your own formatted string?

In [11]:
# To do: Practice string formatting


Just a heads up, the method we just went over is the most recent way to format strings in Python. However, you might stumble upon some other styles out there. Here are a couple examples:

In [12]:
# Other styles of string formatting
name = 'Bob'
age = 20
print(name, "is age", str(age))
print("%s is age %d"%(name, age))

Bob is age 20
Bob is age 20


An even newer way to format strings is with f-strings.

In [13]:
# Newer style of string formatting
print(f'{name} is age {age}') # f-string - note the f

Bob is age 20


### Booleans

Booleans represent binary ```True``` or ```False``` statements. They may be returned from the ```bool(...)``` function or output from boolean operators (below).

For the purpose of control flow statements the following objects would be considered as ```False```:
- integer zero (0)
- float zero (0.0)
- ```None``` keyword
- empty lists, dictionaries, tuples, arrays etc (e.g. (), [], {})

Every other object would be considered ```True``` .

**To do**

Explore this by changing ```my_var``` to different variables.

In [14]:
# To do: Try changing the objects assigned to my_var
# Try: 0, 1, None, an empty list [], a non-empty list [1,2,3], etc.
my_var = 0
if my_var:
    print("is true")

### Dynamical Typing

It's worth mentioning that Python variables are not **statically typed**. What does that mean? Well, you don't need to declare variables before you use them or specify their type. In Python, every variable is an object. For instance, you can declare simple variables right within a print statement and even perform calculations on them without having to declare their type beforehand. Here's an example:

In [15]:
my_var = 5 + 2.3
print("The sum of 5 and 2.3 is {}".format(my_var))

The sum of 5 and 2.3 is 7.3


This is the same as

In [16]:
print("The sum of 5 and 2.3 is {}".format(5 + 2.3))

The sum of 5 and 2.3 is 7.3


## 1.2. Operators

The basic math operators are:
- addition (```+```)
- subtraction (```-```)
- multiplication (```*```)
- division (```/``` or ```//```)

Try out some simple math operations:

In [17]:
print('Addition:', 2 + 3)
print('Subtraction:', 2 - 3)
print('Multiplication:', 2*3)
print('Division: {:.3f}'.format(2/3))
print('Whole (or integer) division:', 2//3)

Addition: 5
Subtraction: -1
Multiplication: 6
Division: 0.667
Whole (or integer) division: 0


The modulus operator (```%```) returns the integer remainder following division:

In [18]:
a = 9
b = 5
print('The remainder following division of {} by {} is {}'.format(a, b, a%b))

The remainder following division of 9 by 5 is 4


Using ```*``` twice (```**```) results in the power operator

In [19]:
a = 2
b = 4
print('{} to the power {} is {}'.format(a, b, a**b))

2 to the power 4 is 16


**To do**

Try out some other arithmetic expressions.

In [20]:
# To do: Try other arithmetic expressions


Operators also work on strings. You can use ```+``` and ```*``` to concatenate strings for example:

In [21]:
print('hello' + 'hello')
print('hello'*10)

hellohello
hellohellohellohellohellohellohellohellohellohello


In your Python script, you can transform any number of variables into strings. You can use ```str()``` or ```{ } ```  in combination with ```str.format``` , or include them in a `format string`. It's as simple as that!

In [22]:
a = 10

# here the integer variable a is cast as a string; otherwise python automatically assumes it is an int
print('hello ' + str(a))

hello 10


### Boolean expressions (Conditions)

Boolean expressions are pretty straightforward - they always return either `True ` or `False`. We often use them to set conditions for `if` and `while` statements. Let's have a look at a few examples:

- Exactly equals to (```==```)
- Comparators: greater than ```>```, less than ```<```, greater than or equal to ```>=```, less than or equal to ```<=```
- Is not equal to (```!=```)
- Inverse (opposite) (```not```)
- Object identity (or non-identity): ```is``` or ```is not```
- Containment (of non-containment): ```in``` or ```not in```

Conditions containing boolean operators ``` == > < ``` are formatted as:

In [23]:
a = 10

print(a == 10)
print(a < 12)
print(a > 20)

True
True
False


Using "not" before a boolean expression inverts it:

In [24]:
a = 10
b = 12

print(a != b)
print(not a == b)

True
True


If you're looking to verify whether two variables are pointing to the same object, you'd use ```is``` or ```is not``` . This is different from ```==``` and ```!=``` in the sense that they're checking if the objects themselves are identical, not just their *values* (which is what `==` does). This functionality shines best when working with lists, which we'll be discussing in the next [section](#lists). Let's keep going!

In [25]:
list_a = [1,2,3]
list_b = list_a # list_b is the same list as list_a
list_c = [1,2,3] # list_c is a new list, that happens to have the same values

print(list_a is list_b)
print(list_a == list_b)
print(list_a is list_c)
print(list_a == list_c)

True
True
False
True


When you want to see if an item is present in a list (which we'll talk about in detail later), you can use ```in``` or ```not in```. Simple as that! (described [below](#lists))

In [26]:
my_list = [1,2,3,4]

print(4 in my_list)
print(5 in my_list)

True
False


When you're working with two conditional statements, you can tie them together (concurrent) using `and` or `or`. If you use and, both conditions have to be true for the combined condition to give you a `True`. On the other hand, with or, just one true condition is enough for the combo to return `True`.

In [27]:
a = 10
b = 12
print(a == b)
print(a < 15 and b < 10)
print(a < 15 or b < 10)

False
False
True


**To do**

Your turn. Let's put this into practice. Go ahead and try creating some examples of your own. I'm sure you'll do great!

In [28]:
# To do: Try out some more examples


## Exercise 1. Variables, Operators and Conditions

**Exercise 1.1.** Playing with the print function and string formatting

In [29]:
# Complete Ex 1.1 below; responding below each comment block

# Q1 define variables
# e.g. a=5; b=10; teststr='Hello World'


# Q2 Practice print statements e.g. print('hello world')
#


# Q3 also try printing the variables you created for Q1
# you will have to cast numbers as strings or combine within format strings


# Q4 Try adding the variable 'a' to variable 'teststr' within a print statement
#   (there are a least 2 ways of doing this, try all)



**Exercise 1.2.** Try some simple operations

In [30]:
# Complete Ex 1.2 below; responding below each comment

# Q1 attempt simple simple math operations, print the output
# e.g.


# Q2 combinations of math operators try combining math operators e.g. a*a+b - a/b



**Exercise 1.3.** Experiment with conditions

In [31]:
# Complete Ex 1.3 below; responding below each comment

# Q1 define variables (completed for you)
a=5
b=10
teststr1='Hello'
teststr2='World'

# Q2 complete and evaluate the following conditional statements
print('a is exactly equal to b',)
print('Twice a is exactly equal to b',)
print('a is greater than b ',)
print('a is less than b',)
print('a is b',)
print('2*a is b',)

# Q3 combine statements using and/or statements e.g. 'a == b or b> a';
#try different combinations; print out


# Q4 try inverting your previous statements with a not;


# Q5 what happens when you negate a statement joined by an 'and' ;
# note that if you use a combination of conditions these must be placed in bracket preceded by not



a is exactly equal to b
Twice a is exactly equal to b
a is greater than b 
a is less than b
a is b
2*a is b


<a id='lists'></a>

## 1.3. Lists

A list in Python is like a treasure chest of ordered items. These items, or elements, don't have to be of the same kind - they can be a mix of numbers, strings, or any other object types. The coolest part? Lists can even contain other lists within them, like nesting dolls! Here are a few examples of lists:

In [32]:
emptylist = [] # An empty list
integerlist = [1,2,3,4,5,6] # A list of integers
stringlist = ['string1', 'string2', 'string3'] # A list of strings
mixedlist = [10, "some string", 4.2, 2, 'some other string'] # A list of mixed data types
nestedlist = [['dog','cat','pig'], [1,2,3,4], [10,"some string",4.2,2,'some other string'] ] # a nested list  - note sublists do not have to have same lengths

### Indexing and slicing

Lists, tuples and strings are what as known as sequential data types. This means that they can be manipulated in ways similar to arrays in Matlab and C++. Do note though, we'll be handling matrices and numeric arrays separately using the Numpy package, which we'll dive into later in this week's lectures.

Because strings and lists behave like array-like objects, you can index and slice out individual elements or even groups of elements from them.

** <font color='red'>Heads up! In Python, all array-like objects start their indexing from 0, not 1 (as in Matlab)</font>  **

Now, let's see this in action with the list objects we've defined above:

In [33]:
teststr = 'Hello World'

print('The third element of integerlist is', integerlist[2])
print('The fourth element of mixedlist is', mixedlist[3])
print('The seventh element of teststr is', teststr[6])

The third element of integerlist is 3
The fourth element of mixedlist is 2
The seventh element of teststr is W


You can totally do indexing in reverse too! When we talk about indexing, we usually think about going from the start and counting forward. But here's the cool part: you can flip it around and count backward instead!

Isn't it great to have options? In some programming languages, like Python, you can use negative indexes to access elements from the end of a sequence.

So, next time you're working with a list or an array, remember that reverse indexing is your new friend. It opens up a whole new world of possibilities! Give it a try and have fun exploring this neat feature.

In [34]:
print('The last element of integerlist is', integerlist[-1])

The last element of integerlist is 6


We can also slice different elements of lists using syntax ```my_list[start:stop:step]```.

Slicing is an awesome feature that lets you extract different elements from a list using the syntax ```my_list[start:stop:step]```.

But here's an important detail to keep in mind: when you use **slice indexing, it takes all the elements up to, but not including, the last index you specify**. So it's like saying, "Give me everything up to that point, but don't include the element at the last index."

Let's take a closer look with an example to make it crystal clear:

In [35]:
# note slice indexing takes all elements up to but not including the last index
print('Elements 2-3 of integerlist', integerlist[2:4])
print('Slicing from the beginning to the 5th element', integerlist[:5])
print('slicing from the 5th element to the end', integerlist[4:])
print('slicing from the 5th element to the penultimate value', integerlist[4:-1])

Elements 2-3 of integerlist [3, 4]
Slicing from the beginning to the 5th element [1, 2, 3, 4, 5]
slicing from the 5th element to the end [5, 6]
slicing from the 5th element to the penultimate value [5]


Using the `step` notation in slicing allows you to extract every other element within a range. It's like skipping some elements and cherry-picking the ones you want.

In [36]:
print('Every other element of integerlist from beginning to end', integerlist[0::2])

Every other element of integerlist from beginning to end [1, 3, 5]


You can use the `in` operator to check whether elements are present within a list. It's like having a handy tool to quickly find out if a particular element exists in your list.

In [37]:
print('Is 3 in integerlist?', 3 in integerlist)
print('Is 0 in integerlist?', 0 in integerlist)

Is 3 in integerlist? True
Is 0 in integerlist? False


**To do**

Let's have some fun trying out indexing and slicing with the provided lists and strings, and even create our very own lists to play around with. Get ready for some hands-on experimentation! Do they return what you expect?

In [38]:
# To do - try indexing and slicing some lists and strings


### Assignment and mutation

You can increase the length of a list using the `append()` function! It's like giving your list a growth spurt and adding new elements to it.

By using the `append()` function, you can easily add new elements to the end of your list. It's a handy way to dynamically increase the size of your list as you go.

In [39]:
integerlist.append(7)
print('integerlist:', integerlist)

integerlist: [1, 2, 3, 4, 5, 6, 7]


Or insert to the middle of a list using ```insert(index,value)```

In [40]:
integerlist.insert(3, 100)
print('new integer list', integerlist)

new integer list [1, 2, 3, 100, 4, 5, 6, 7]


When it comes to appending or inserting more than one object to a list, the `append()` and `insert()` methods are designed to handle a single argument at a time.

Another approach is to use **concatenation**, which is performed using the `+` operator.

In [41]:
mergedlist = integerlist + stringlist
print(mergedlist)

[1, 2, 3, 100, 4, 5, 6, 7, 'string1', 'string2', 'string3']


If you want to find out the length of a list, you can use the `len()` function. It's like a measuring tape for lists, giving you the number of elements it contains.

In [42]:
print('The length of integerlist is', len(integerlist))
print('The length of teststr is', len(teststr))

The length of integerlist is 8
The length of teststr is 11


Note, lists are **mutable** which means you can modify them by swapping out items with new ones. It's like having the power to update and change the elements within a list.

In [43]:
stringlist[2] = 3
print(stringlist)

['string1', 'string2', 3]


On the other hand strings and tuples are _**immutable**_; you cannot change them once created. Try running the following line of code and see what happens.

In [44]:
teststr = 'Hello World'
try: # The try-except statements are used to catch exceptions (errors)
    teststr[2]='a'
except Exception as e:
    print('Error:', type(e))

Error: <class 'TypeError'>


## 1.4. Tuples

Tuples are immutable lists. They are defined analogously to lists, but with a crucial difference:

- Once a tuple is created, we cannot add, remove or change items.

- Tuples are defined by enclosing a set of elements in parentheses instead of square brackets (which are used for lists).

Let's take a look at an example to see how tuples work:

In [45]:
mytuple = (10, "Dog's", 4.2)
print('mytuple 2nd item:', mytuple[1])

mytuple 2nd item: Dog's


Tuples have certain advantages over lists, and their faster indexing speed is one of them. Since tuples are immutable, the Python interpreter can optimize their internal representation, making indexing operations faster compared to lists.

In scenarios where program runtime is crucial and you have a collection of items that you know should remain fixed and unchangeable, using tuples can be advantageous. By using tuples, you ensure that the elements are permanently fixed in the structure, which allows for efficient indexing operations.

## 1.5 Dictionaries

In many ways, dictionaries share some similarities with lists, such as the ability to contain any type of object and be easily modified or appended at runtime. However, dictionaries have some distinct characteristics that set them apart.

- One key difference is that dictionaries are unordered, meaning the elements within them do not have a specific order or sequence.

- Instead of using numerical indices like lists, dictionaries use keys for indexing. Each key in a dictionary is associated with a value, allowing for efficient retrieval and modification of data based on those keys.

Dictionaries can be defined in one line using curly braces `{}` or incrementally and specifying key-value pairs separated by colons. Here's an example:

In [46]:
# empty dictionary - note curly brackets
mydict = {}

# define each key-value pair one at a time
mydict['name'] ='John' # The key is 'name' the value is 'John')
mydict['age'] = 23
mydict['job'] = 'Lecturer'
mydict['height'] = 190
print(mydict)

# inline definition (all key-value pairs initialised together in one line, separated by commas)
# in this notation, keys come first, foloowed by colon, followed by the object they reference
mydict_inline = {'name':'John', 'age':23, 'job':'Lecturer', 'height':190}
print(mydict_inline)

{'name': 'John', 'age': 23, 'job': 'Lecturer', 'height': 190}
{'name': 'John', 'age': 23, 'job': 'Lecturer', 'height': 190}


The keys e.g. 'name', 'age', etc. can be any immutable type. **This includes tuples**.

In [47]:
mydict[5] = 'val1'
mydict[3.2413] =' val2'
mydict[(1,2,3)] = 'val3'

The objects ('Dave', 23, 'Lecturer', 190) can be **any type** which means dictionaries can store lists.

In [48]:
mydict = {}
mydict['name'] = 'Dave'
mydict['age'] = 23
mydict['job'] = 'Lecturer'
mydict['height'] = 190
mydict['phones'] = ['780-555-0123' , '780-555-4810']

What's also (hopefully) clear from the above is that you can easy append new keys to the dict at any time.

In [49]:
mydict['weight'] = 80

Further, **dictionary values are mutable** which means they can be changed.

In [50]:
mydict['name'] = 'June'
print(mydict)

{'name': 'June', 'age': 23, 'job': 'Lecturer', 'height': 190, 'phones': ['780-555-0123', '780-555-4810'], 'weight': 80}


Dictionary elements can be deleted using ```del mydict[key]```

In [51]:
del mydict['name']
print(mydict)

{'age': 23, 'job': 'Lecturer', 'height': 190, 'phones': ['780-555-0123', '780-555-4810'], 'weight': 80}


But, what happens, if we try to access a key, i.e. a city, which is not contained in the dictionary? We raise a ```KeyError:```

In [52]:
try:
    print(mydict['city'])
except Exception as e:
    print('Error:', type(e))

Error: <class 'KeyError'>


Note, dictionaries are not ordered therefore they cannot be searched sequentially, indexed or sliced (although key iterators exist and will be described in the next notebook). Otherwise many of the same functions that operate on lists, operate on dictionaries:

In [53]:
print('Number of key-value pairs in mydict:', len(mydict))
print("Is key 'name' in mydict:", 'name' in mydict) # note this is case sensitive; try changing 'name' to 'Name'

Number of key-value pairs in mydict: 5
Is key 'name' in mydict: False


## Exercise 2: Dictionaries and Lists

**Exercise 2.1.** Lists:

- Create an list of integers
- Estimate the length of the list; print it out
- Index the list at different points along its length
- Take a slice of a subset of elements from the list
- Append the list with a new item of a different type

In [54]:
#Complete responses to Ex 2.1 here, e.g. mylist=[1,2,3,4,5]


# index elements at different lengths along the list


# index the last element of your list


# slice from the second to the third value


# append



**Exercise 2.2.** Operations on sequential data types
- Concatenate two strings, and two lists
- Concatenate 10 copies of each string

In [55]:
#Complete responses to Ex 2.2 below
string1='Hello'
string2='World'
list1=['Hello', 'World']
list2=["I'm", 'ready', 'to' 'Python']

# Important - Never name your variables after data types
#i.e. str='mystring', list=['some', 'list'] should never be used

# Q1 Concatenate two strings, and two lists


# Q2  Concatenate 10 copies of each string



**Exercise 2.3.** Mutable and Immutable objects
- Try changing different elements of this string and list
- Create a tuple, try to change

In [56]:
#Complete responses to Ex 2.3 here
mylist=['Is', 'this' ,'list' ,'mutable']
mystring='Is this string Mutable'

# change element 3 of mylist


# change element 2 of mystring

